export const USERS = [
  {
    user_id: "demo_alexa",
    first_name: "Alexa",
    last_name: "Demo",
    email: "alexa@example.com",
    region: "IN",
    household_size: 1,
    baseline_monthly_kgCO2: 120,
  },
  {
    user_id: "user_01",
    first_name: "Rahul",
    last_name: "Patel",
    email: "rahul@example.com",
    region: "IN",
    household_size: 3,
    baseline_monthly_kgCO2: 420,
  },
  {
    user_id: "user_02",
    first_name: "Sophia",
    last_name: "King",
    email: "sophia@example.com",
    region: "UK",
    household_size: 1,
    baseline_monthly_kgCO2: 95,
  },
]

export const DAILY_LOGS = [
  {
    log_id: "log_0001",
    user_id: "demo_alexa",
    date: "2025-01-01",
    event_type: "commute",
    detail: "car to work",
    distance_km: 5,
    estimated_co2_kg: 1.8,
  },
  {
    log_id: "log_0002",
    user_id: "demo_alexa",
    date: "2025-01-01",
    event_type: "meal",
    detail: "beef lunch",
    estimated_co2_kg: 4.5,
  },
  {
    log_id: "log_0003",
    user_id: "demo_alexa",
    date: "2025-01-01",
    event_type: "device",
    detail: "tv watching",
    device_hours: 2.5,
    estimated_co2_kg: 0.06,
  },
  {
    log_id: "log_0004",
    user_id: "demo_alexa",
    date: "2025-01-02",
    event_type: "commute",
    detail: "bus to work",
    distance_km: 5,
    estimated_co2_kg: 0.6,
  },
  {
    log_id: "log_0005",
    user_id: "demo_alexa",
    date: "2025-01-02",
    event_type: "meal",
    detail: "veg lunch",
    estimated_co2_kg: 1.2,
  },
  {
    log_id: "log_0006",
    user_id: "demo_alexa",
    date: "2025-01-02",
    event_type: "device",
    detail: "work laptop",
    device_hours: 6,
    estimated_co2_kg: 0.18,
  },
  {
    log_id: "log_0007",
    user_id: "demo_alexa",
    date: "2025-01-03",
    event_type: "commute",
    detail: "cycle to work",
    distance_km: 5,
    estimated_co2_kg: 0.0,
  },
  {
    log_id: "log_0008",
    user_id: "demo_alexa",
    date: "2025-01-03",
    event_type: "meal",
    detail: "vegan dinner",
    estimated_co2_kg: 0.8,
  },
  {
    log_id: "log_0009",
    user_id: "demo_alexa",
    date: "2025-01-04",
    event_type: "commute",
    detail: "car to work",
    distance_km: 5,
    estimated_co2_kg: 1.8,
  },
  {
    log_id: "log_0010",
    user_id: "demo_alexa",
    date: "2025-01-05",
    event_type: "meal",
    detail: "chicken lunch",
    estimated_co2_kg: 2.1,
  },
]

export const ACTIONS_CATALOG = [
  {
    action_id: "A001",
    title: "Walk or cycle for short commutes",
    category: "commute",
    est_saved_kg: 0.9,
    friction: "low",
    duration_mins: 15,
    tags: ["health", "zero-cost"],
  },
  {
    action_id: "A002",
    title: "Switch one meat meal to plant-based",
    category: "diet",
    est_saved_kg: 3.3,
    friction: "medium",
    duration_mins: 20,
    tags: ["food", "groceries"],
  },
  {
    action_id: "A003",
    title: "Delay AC by 1 degree and use fan",
    category: "home_energy",
    est_saved_kg: 0.4,
    friction: "low",
    duration_mins: 60,
    tags: ["comfort", "savings"],
  },
  {
    action_id: "A004",
    title: "Use LED bulbs instead of incandescent",
    category: "home_energy",
    est_saved_kg: 0.15,
    friction: "low",
    duration_mins: 10,
    tags: ["lighting", "savings"],
  },
  {
    action_id: "A005",
    title: "Reduce device screen time by 1 hour",
    category: "device",
    est_saved_kg: 0.05,
    friction: "medium",
    duration_mins: 5,
    tags: ["health", "wellness"],
  },
]

export const USER_PROGRESS = [
  {
    progress_id: "p0001",
    user_id: "demo_alexa",
    date: "2025-01-01",
    action_id: "A001",
    completed: true,
    points_earned: 5,
  },
  {
    progress_id: "p0002",
    user_id: "demo_alexa",
    date: "2025-01-02",
    action_id: "A002",
    completed: true,
    points_earned: 8,
  },
  {
    progress_id: "p0003",
    user_id: "demo_alexa",
    date: "2025-01-02",
    action_id: "A003",
    completed: false,
    points_earned: 0,
  },
  {
    progress_id: "p0004",
    user_id: "demo_alexa",
    date: "2025-01-03",
    action_id: "A001",
    completed: true,
    points_earned: 5,
  },
  {
    progress_id: "p0005",
    user_id: "demo_alexa",
    date: "2025-01-04",
    action_id: "A005",
    completed: true,
    points_earned: 3,
  },
  {
    progress_id: "p0006",
    user_id: "demo_alexa",
    date: "2025-01-05",
    action_id: "A002",
    completed: true,
    points_earned: 8,
  },
]

export const HOME_APPLIANCES = [
  {
    appliance_id: "AC001",
    user_id: "demo_alexa",
    name: "Air Conditioner",
    type: "cooling",
    power_watts: 1500,
    usage_hours_daily: 4,
    efficiency_rating: "5-star",
    age_years: 3,
    estimated_monthly_kgCO2: 45.0,
  },
  {
    appliance_id: "REF001",
    user_id: "demo_alexa",
    name: "Refrigerator",
    type: "refrigeration",
    power_watts: 400,
    usage_hours_daily: 24,
    efficiency_rating: "5-star",
    age_years: 2,
    estimated_monthly_kgCO2: 28.8,
  },
  {
    appliance_id: "WM001",
    user_id: "demo_alexa",
    name: "Washing Machine",
    type: "laundry",
    power_watts: 2000,
    usage_hours_daily: 1,
    efficiency_rating: "4-star",
    age_years: 5,
    estimated_monthly_kgCO2: 6.0,
  },
  {
    appliance_id: "TV001",
    user_id: "demo_alexa",
    name: "LED Television",
    type: "entertainment",
    power_watts: 100,
    usage_hours_daily: 5,
    efficiency_rating: "5-star",
    age_years: 2,
    estimated_monthly_kgCO2: 1.5,
  },
  {
    appliance_id: "WH001",
    user_id: "demo_alexa",
    name: "Water Heater",
    type: "heating",
    power_watts: 3000,
    usage_hours_daily: 2,
    efficiency_rating: "3-star",
    age_years: 8,
    estimated_monthly_kgCO2: 18.0,
  },
  {
    appliance_id: "OVEN001",
    user_id: "demo_alexa",
    name: "Electric Oven",
    type: "cooking",
    power_watts: 2500,
    usage_hours_daily: 1,
    efficiency_rating: "4-star",
    age_years: 4,
    estimated_monthly_kgCO2: 7.5,
  },
  {
    appliance_id: "LIGHT001",
    user_id: "demo_alexa",
    name: "LED Lighting System",
    type: "lighting",
    power_watts: 300,
    usage_hours_daily: 6,
    efficiency_rating: "5-star",
    age_years: 1,
    estimated_monthly_kgCO2: 0.54,
  },
  {
    appliance_id: "PC001",
    user_id: "demo_alexa",
    name: "Desktop Computer",
    type: "computing",
    power_watts: 500,
    usage_hours_daily: 4,
    efficiency_rating: "4-star",
    age_years: 3,
    estimated_monthly_kgCO2: 0.6,
  },
]

export const ENERGY_LOGS = [
  {
    energy_log_id: "EL001",
    user_id: "demo_alexa",
    appliance_id: "AC001",
    date: "2025-01-01",
    hours_used: 4,
    energy_consumed_kwh: 6.0,
    estimated_co2_kg: 1.8,
    cost_usd: 0.72,
  },
  {
    energy_log_id: "EL002",
    user_id: "demo_alexa",
    appliance_id: "REF001",
    date: "2025-01-01",
    hours_used: 24,
    energy_consumed_kwh: 9.6,
    estimated_co2_kg: 2.88,
    cost_usd: 1.15,
  },
  {
    energy_log_id: "EL003",
    user_id: "demo_alexa",
    appliance_id: "WM001",
    date: "2025-01-01",
    hours_used: 1,
    energy_consumed_kwh: 2.0,
    estimated_co2_kg: 0.6,
    cost_usd: 0.24,
  },
  {
    energy_log_id: "EL004",
    user_id: "demo_alexa",
    appliance_id: "TV001",
    date: "2025-01-01",
    hours_used: 5,
    energy_consumed_kwh: 0.5,
    estimated_co2_kg: 0.15,
    cost_usd: 0.06,
  },
  {
    energy_log_id: "EL005",
    user_id: "demo_alexa",
    appliance_id: "WH001",
    date: "2025-01-01",
    hours_used: 2,
    energy_consumed_kwh: 6.0,
    estimated_co2_kg: 1.8,
    cost_usd: 0.72,
  },
  {
    energy_log_id: "EL006",
    user_id: "demo_alexa",
    appliance_id: "AC001",
    date: "2025-01-02",
    hours_used: 3.5,
    energy_consumed_kwh: 5.25,
    estimated_co2_kg: 1.575,
    cost_usd: 0.63,
  },
  {
    energy_log_id: "EL007",
    user_id: "demo_alexa",
    appliance_id: "REF001",
    date: "2025-01-02",
    hours_used: 24,
    energy_consumed_kwh: 9.6,
    estimated_co2_kg: 2.88,
    cost_usd: 1.15,
  },
  {
    energy_log_id: "EL008",
    user_id: "demo_alexa",
    appliance_id: "OVEN001",
    date: "2025-01-02",
    hours_used: 1,
    energy_consumed_kwh: 2.5,
    estimated_co2_kg: 0.75,
    cost_usd: 0.3,
  },
  {
    energy_log_id: "EL009",
    user_id: "demo_alexa",
    appliance_id: "TV001",
    date: "2025-01-02",
    hours_used: 4,
    energy_consumed_kwh: 0.4,
    estimated_co2_kg: 0.12,
    cost_usd: 0.05,
  },
  {
    energy_log_id: "EL010",
    user_id: "demo_alexa",
    appliance_id: "AC001",
    date: "2025-01-03",
    hours_used: 2,
    energy_consumed_kwh: 3.0,
    estimated_co2_kg: 0.9,
    cost_usd: 0.36,
  },
  {
    energy_log_id: "EL011",
    user_id: "demo_alexa",
    appliance_id: "WM001",
    date: "2025-01-03",
    hours_used: 1.5,
    energy_consumed_kwh: 3.0,
    estimated_co2_kg: 0.9,
    cost_usd: 0.36,
  },
  {
    energy_log_id: "EL012",
    user_id: "demo_alexa",
    appliance_id: "REF001",
    date: "2025-01-03",
    hours_used: 24,
    energy_consumed_kwh: 9.6,
    estimated_co2_kg: 2.88,
    cost_usd: 1.15,
  },
  {
    energy_log_id: "EL013",
    user_id: "demo_alexa",
    appliance_id: "LIGHT001",
    date: "2025-01-03",
    hours_used: 6,
    energy_consumed_kwh: 1.8,
    estimated_co2_kg: 0.54,
    cost_usd: 0.22,
  },
  {
    energy_log_id: "EL014",
    user_id: "demo_alexa",
    appliance_id: "AC001",
    date: "2025-01-04",
    hours_used: 4.5,
    energy_consumed_kwh: 6.75,
    estimated_co2_kg: 2.025,
    cost_usd: 0.81,
  },
  {
    energy_log_id: "EL015",
    user_id: "demo_alexa",
    appliance_id: "WH001",
    date: "2025-01-04",
    hours_used: 2.5,
    energy_consumed_kwh: 7.5,
    estimated_co2_kg: 2.25,
    cost_usd: 0.9,
  },
  {
    energy_log_id: "EL016",
    user_id: "demo_alexa",
    appliance_id: "TV001",
    date: "2025-01-04",
    hours_used: 6,
    energy_consumed_kwh: 0.6,
    estimated_co2_kg: 0.18,
    cost_usd: 0.07,
  },
  {
    energy_log_id: "EL017",
    user_id: "demo_alexa",
    appliance_id: "PC001",
    date: "2025-01-04",
    hours_used: 4,
    energy_consumed_kwh: 2.0,
    estimated_co2_kg: 0.6,
    cost_usd: 0.24,
  },
  {
    energy_log_id: "EL018",
    user_id: "demo_alexa",
    appliance_id: "REF001",
    date: "2025-01-04",
    hours_used: 24,
    energy_consumed_kwh: 9.6,
    estimated_co2_kg: 2.88,
    cost_usd: 1.15,
  },
  {
    energy_log_id: "EL019",
    user_id: "demo_alexa",
    appliance_id: "AC001",
    date: "2025-01-05",
    hours_used: 3,
    energy_consumed_kwh: 4.5,
    estimated_co2_kg: 1.35,
    cost_usd: 0.54,
  },
  {
    energy_log_id: "EL020",
    user_id: "demo_alexa",
    appliance_id: "REF001",
    date: "2025-01-05",
    hours_used: 24,
    energy_consumed_kwh: 9.6,
    estimated_co2_kg: 2.88,
    cost_usd: 1.15,
  },
]
