import { getUserAnalytics, getComparisonAnalytics } from "./analytics"

export interface ReportData {
  userId: string
  timestamp: string
  summary: {
    currentMonthEmissions: number
    baselineMonthly: number
    totalSaved: number
    percentageChange: number
  }
  categoryBreakdown: Array<{ name: string; value: number; percentage: number }>
  weeklyTrend: Array<{ day: string; emissions: number; actions: number }>
  forecast: { reduction: number; estimatedEmissions: number }
  actionsCompleted: number
  greenPoints: number
}

export function generateReportData(userId: string): ReportData {
  const analytics = getUserAnalytics(userId)

  return {
    userId,
    timestamp: new Date().toISOString(),
    summary: {
      currentMonthEmissions: analytics.currentMonthEmissions,
      baselineMonthly: analytics.baselineMonthly,
      totalSaved: analytics.totalSaved,
      percentageChange: analytics.percentageChange,
    },
    categoryBreakdown: analytics.categoryBreakdown,
    weeklyTrend: analytics.weeklyTrend,
    forecast: analytics.forecast30Days,
    actionsCompleted: analytics.actionsCompleted,
    greenPoints: analytics.totalPoints,
  }
}

export function generateComparativeReport() {
  const comparison = getComparisonAnalytics()

  return {
    timestamp: new Date().toISOString(),
    totalUsers: comparison.userCount,
    averageBaseline: comparison.avgBaseline,
    averageCurrentEmissions: comparison.avgCurrentEmissions,
    totalSavedAcrossUsers: comparison.totalSavedAcrossUsers,
    averageReductionPercentage: comparison.avgReductionPercentage,
    userDetails: comparison.users.map((u) => ({
      name: u.name,
      baseline: u.baseline,
      current: u.analytics.currentMonthEmissions,
      saved: u.analytics.totalSaved,
      actions: u.analytics.actionsCompleted,
    })),
  }
}

export function generateTextSummary(userId: string): string {
  const analytics = getUserAnalytics(userId)
  const date = new Date().toLocaleDateString()

  return `
CARBON FOOTPRINT REPORT
Generated: ${date}
User: ${userId}

SUMMARY
Current Monthly Emissions: ${analytics.currentMonthEmissions} kg CO₂
Baseline: ${analytics.baselineMonthly} kg CO₂
Total Saved: ${analytics.totalSaved} kg CO₂
Reduction: ${Math.abs(analytics.percentageChange)}%

TOP EMITTING CATEGORIES
${analytics.categoryBreakdown
  .slice(0, 3)
  .map((cat) => `${cat.name}: ${cat.percentage}% (${cat.value} kg)`)
  .join("\n")}

ACTIONS & PROGRESS
Actions Completed: ${analytics.actionsCompleted}
Green Points: ${analytics.totalPoints}

30-DAY FORECAST
Projected Reduction: ${analytics.forecast30Days.reduction}%
Estimated Emissions: ${analytics.forecast30Days.estimatedEmissions} kg CO₂

---
Emission factors sourced from DEFRA, IEA, and EPA
Report generated by CarbonAI
  `.trim()
}
